### ISSUE TITLE
Need to update for the 2 parameter case.

### ISSUE THREAD

**Issue by davidshaw2018** [ihmeuw-msca/modrover#15]
Need to update for the 2 parameter case. 

We can have >n coefficients for the parent model, if covariates are duplicated across parameters. Order of parameters and coefficients determined by regmod class itself

_Originally posted by @davidshaw2018 in https://github.com/ihmeuw-msca/modrover/pull/14#discussion_r1123884540_

**Comment by davidshaw2018** [comment]
Need an ordered index of explore/fixed covariates for 2 parameter case, use the regmod model to determine it.

**Comment by zhengp0** [comment]
This has been resolved in #16
