### ISSUE TITLE
KeyError related to holdout indexing in modelhub._fit_model()

### ISSUE THREAD

**Issue by kels271828** [ihmeuw-msca/modrover#4]
If modelhub._fit_model is called without passing a data frame, the data frame is loaded from from the input path and then filtered to remove holdout data. However, the line to filter the data frame is written incorrectly and throws a KeyError. Compare the [line in _fit_model](https://github.com/ihmeuw-msca/modrover/blob/85907157e20dc842cf79d217b54b70bea2ce03bc/src/modrover/modelhub.py#L68) to the [line in _run_model](https://github.com/ihmeuw-msca/modrover/blob/85907157e20dc842cf79d217b54b70bea2ce03bc/src/modrover/modelhub.py#L151).

Additionally, if a data frame is not passed, a str col_holdout should be passed, because model.specs.col_holdout is supposed to be a tuple of str and not a str (though there isn't a check when creating an instance of modelhub), so it is not clear which holdout set to filter out. Alternatively, you could just make the data frame a required argument. It only gets called from modelhub._run_model, which does pass a data frame).

**Comment by zhengp0** [comment]
Currently when we fit a model we will always pass in a dataframe
https://github.com/ihmeuw-msca/modrover/blob/main/src/modrover/learner.py#L265
And the holdouts are used outside of the `_fit` function to subset the training data
https://github.com/ihmeuw-msca/modrover/blob/main/src/modrover/learner.py#L128-L136
