### ISSUE TITLE
Order of `required_covs` in `visualize()`

### ISSUE THREAD

**Issue by kels271828** [ihmeuw-msca/modrover#5]
If the order of covariate names in `required_covs` does not match the directory names in the saved outputs, the triangle marker for "single_model" will be incorrect (most will be plotted at zero instead of the correct coefficient value).

https://github.com/ihmeuw-msca/modrover/blob/85907157e20dc842cf79d217b54b70bea2ce03bc/src/modrover/visualizer.py#L61

**Comment by zhengp0** [comment]
In the current visualization (#21), we remove the original `required_covs` parameter and always plot the full set.
